# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-bananapi-f3.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-milkv-jupiter.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-orangepi-rv2.dtb

dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3_fpga_1x1.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3_evb.dtb k3_evb2-1.dtb k3_evb2-2.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3_deb1.dtb k3-pico-itx.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3_com260.dtb k3_com260_ifx.dtb k3_com260_ifx2.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3-deepcomputing-fml13v05.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3-firefly-aibox-k3.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3_com260_kit_v02.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3_gemini_c0.dtb k3_gemini_c1.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3_BS01DCMA.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K3) += k3_com260_tq.dtb k3_com260_ifx_tq.dtb
